# Generated by Django 5.2.6 on 2025-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QaqcRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dataset_key", models.CharField(max_length=128)),
                ("batch_id", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("pass", "Pass"), ("fail", "Fail")],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("checks_passed", models.IntegerField(default=0)),
                ("checks_failed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
