# =============================================================================
# Project-level URL configuration.
# =============================================================================
# Mounts each app under its own prefix, plus the legacy REST API
# (/api/schemas/, /api/datasets/) and the OpenAPI docs.
# OIDC routes (/oidc/) are only added when SSO is enabled.
# =============================================================================

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
    SpectacularRedocView,
)

urlpatterns = [
    # Django Admin — separate auth, used by superusers only.
    path('admin/', admin.site.urls),

    # User-facing pages, one app per prefix.
    path('', include('apps.core.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('schemas/', include('apps.schemas.urls')),
    path('datasets/', include('apps.datasets.urls')),
    path('qaqc/', include('apps.qaqc.urls')),
    path('lineage/', include('apps.lineage.urls')),

    # Legacy REST API (predates the Schema.json-driven dynamic tables).
    path('api/schemas/', include('apps.schemas.api_urls')),
    path('api/datasets/', include('apps.datasets.api_urls')),

    # OpenAPI schema + Swagger UI + ReDoc, generated by drf-spectacular.
    path('api/schema/openapi.yaml', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    # Prometheus metrics endpoint (/metrics) provided by django-prometheus.
    path('', include('django_prometheus.urls')),
]

# OIDC callback / login / logout routes — only loaded when SSO is enabled,
# otherwise mozilla_django_oidc isn't even in INSTALLED_APPS.
if not getattr(settings, 'DISABLE_OIDC', True):
    urlpatterns += [
        path('oidc/', include('mozilla_django_oidc.urls')),
    ]

# In DEBUG mode, serve uploaded media and static files directly from
# Django. In production WhiteNoise handles statics and media goes to S3.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
